---
# Vault Event-Driven Automation Rulebook
# This rulebook connects to HCP Vault Dedicated WebSocket event stream
# and processes KV v2 and Database events in real-time
# Note: Each event pattern creates a separate WebSocket connection
# Supported event types: kv-v1/*, kv-v2/*, database/*

- name: HCP Vault Event Monitoring
  hosts: localhost
  sources:
    - gitrgoliveira.vault_eda.vault_events:
        vault_addr: "{{ VAULT_ADDR }}"
        vault_token: "{{ VAULT_TOKEN }}"
        namespace: "{{ VAULT_NAMESPACE | default('admin') }}"
        verify_ssl: true
        ping_interval: 30
        event_paths:
          - "kv-v2/data-write"
          - "kv-v2/data-patch"
          - "kv-v2/data-delete"

  rules:
    # Rule for KV v2 write operations
    - name: on hcp kv write
      condition: event.data.event_type == "kv-v2/data-write"
      action:
        debug:
          msg: >
            🎉 HCP KV Write Event -
            Path: {{ event.data.event.metadata.path }},
            Data Path: {{ event.data.event.metadata.data_path }},
            Operation: {{ event.data.event.metadata.operation }},
            Version: {{ event.data.event.metadata.current_version }}

    # Rule for KV v2 patch operations
    - name: on hcp kv patch
      condition: event.data.event_type == "kv-v2/data-patch"
      action:
        debug:
          msg: >
            ✏️ HCP KV Patch Event -
            Path: {{ event.data.event.metadata.path }},
            Data Path: {{ event.data.event.metadata.data_path }},
            Operation: {{ event.data.event.metadata.operation }}

    # Rule for KV v2 delete operations
    - name: on hcp kv delete
      condition: event.data.event_type == "kv-v2/data-delete"
      action:
        debug:
          msg: >
            🗑️ HCP KV Delete Event -
            Path: {{ event.data.event.metadata.path }},
            Operation: {{ event.data.event.metadata.operation }}

    # Catch-all rule for any HCP Vault event
    - name: on any hcp vault event
      condition: event.data is defined
      action:
        debug:
          msg: >
            🔔 HCP Vault Event -
            Type: {{ event.data.event_type }},
            Namespace: admin,
            Time: {{ event.time | default('N/A') }}